### ISSUE TITLE
Kismet does not find ubertooth

### ISSUE THREAD

**Issue by Bre5933** [greatscottgadgets/ubertooth#299]
### Steps to reproduce
1. Followed build guide
2. Followed README in /host/kismet/plugin-ubertooth
3. Run kismet as root and add source

### Expected behaviour
Ubertooth device should be detected and added to sources

### Actual behaviour
Failed to find type for auto-type source "ubertooth".....

### Version information
**Operating system**: Ubuntu 14.04 LTS

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.0 (2017-03-R2), libbtbb 1.0 (git-1b6084d)

**libbtbb version:**
libubertooth 1.0 (2017-03-R2), libbtbb 1.0 (git-1b6084d)

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: 2017-03-R2 (API:1.02)

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.
Kismet 2013-03-R0
### Output
![image](https://user-images.githubusercontent.com/26638481/34419594-b8e783c0-ebd2-11e7-8efe-4f236b1cf388.png)

**Comment by Bre5933** [comment]
I should add that the device is connected. I can still use the ubertooth spectrum analyzer

**Comment by Bre5933** [comment]
Fixed the issue with a little help from this Hak5 video. 
https://www.google.com/search?client=ubuntu&channel=fs&q=using+kismet+with+ubertooth&ie=utf-8&oe=utf-8#kpvalbx=1
the only issue is one the kismet dir is moved you still need to:
./configure
make && make plugins
sudo make suidinstall
sudo make plugins-install
Add "pcapbtbb" to the "logtypes=..." line in kismet.conf

then cd  to /host/kismet/plugin-ubertooth

and finally make && make install

after that i ran kismet from home directory and added the ubertooth source

**Comment by EMCP** [comment]
I am having similar issues.  Tried latest Kismet source code installation, which failed with the known header issue.. However rolling back to the instructions 2013 Kismet yielded nothing working, no sources detected in Kismet.

You say you got it working by `then cd to /host/kismet/plugin-ubertooth`

but there is no make file in that directory ..

```
pi@raspberrypi:~/Dev/ubertooth-2017-03-R2/host/kismet/plugin-ubertooth $ make && make install
Makefile:7: /usr/src/kismet/Makefile.inc: No such file or directory
make: *** No rule to make target '/usr/src/kismet/Makefile.inc'.  Stop.
```

**Comment by Bre5933** [comment]
I believe you may need to edit the make file in host/kismet/plugin-ubertooth to point at that directory instead of /usr/src/kismet. I'm currently don't have access to the PC I used. Could help you tomorrow though

**Comment by ramamr33** [comment]
Hi All,

I have tried to install the kismet plugin-ubertooth downloaded from Github (https://github.com/greatscottgadgets/ubertooth) but I am still getting the same error:

![image](https://user-images.githubusercontent.com/52582132/61397670-4f5b0e00-a8c2-11e9-9a22-499dd8fc6a5d.png)


I have tried to run make && make install plugins command on the kismet src directory (downloaded from GitHub - https://github.com/kismetwireless/kismet.git) but I am getting stuck with this error as well:

make: *** No targets specified and no makefile found.  Stop.

I confirm 2 files **MakeFile.in** and **MakeFile.inc.in** both exist on the kismet src directory:
![image](https://user-images.githubusercontent.com/52582132/61397147-2c7c2a00-a8c1-11e9-9f13-2ed90f0045d8.png)

Please kindly assist.
Thanks.

**Comment by mikeryan** [comment]
Legacy Kismet is no longer supported by this project.
